version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: cargo build
          command: 'cargo build'
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: cargo test
          command: 'cargo test'