version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: cargo build
          command:
          'curl https://sh.rustup.rs -sSf | sh'
          'cargo build'
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: cargo test
          command: 'cargo test'